### ISSUE TITLE
Generated css file is empty

### ISSUE THREAD

**Issue by 0x241F31** [TobiCham/vite-css-in-js#1] opened 2023-07-07 05:09 UTC
![image](https://github.com/TobiCham/vite-css-in-js/assets/17229619/31e519da-f13d-47f4-b302-e51c93cabbfa)
![image](https://github.com/TobiCham/vite-css-in-js/assets/17229619/418f563f-a2e9-4084-ad1f-24f563d0b856)

**Comment by TobiCham** [comment] 2024-09-29 12:41
I believe the main issue here is the SSR plugin you are using. When attempting to replicate with vite-plugin-ssr, I did encounter the same broken behaviour, but upgrading to the latest version of Vike (i.e. its replacement), the issue was fixed.

I believe the bug was to do with how the old version processed client vs server assets via multiple transforms, but has clearly been fixed upstream.

Closing for now,  but you're welcome to reopen if the issue is encountered again.

**Closed as completed by TobiCham** 2024-09-29 12:41 UTC
